[package]
name = "http2_client"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
h2 = "0.3"
hyper = { version = "0.14", features = ["http2"] }
tokio-rustls = "0.22.0"
webpki-roots = "0.22"
structopt = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
